// Generated by npm run build:blog. Edit content/posts/*.md instead.
window.BLOG_POSTS = [
  {
    "title": "Small Language Models Hallucinate Knowing Something's Off",
    "description": "Research on epistemic uncertainty detection in language models and how small models suppress detected uncertainty.",
    "date": "2026-01-24",
    "displayDate": "January 24, 2026",
    "label": "research · epistemic uncertainty",
    "source": "LessWrong",
    "external": true,
    "url": "https://www.lesswrong.com/posts/cgCeqi8cDn9RnDdQA/small-language-models-hallucinate-knowing-something-s-off"
  }
];
