import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = join(root, 'content', 'posts');
const outputDir = join(root, 'posts');
const template = await readFile(join(root, 'templates', 'post.html'), 'utf8');

const escapeHtml = (value = '') => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;');

function parsePost(source, filename) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: missing front matter`);

  const metadata = Object.fromEntries(
    match[1].split(/\r?\n/).filter(Boolean).map(line => {
      const separator = line.indexOf(':');
      if (separator < 1) throw new Error(`${filename}: invalid front matter line: ${line}`);
      return [line.slice(0, separator).trim(), line.slice(separator + 1).trim()];
    })
  );

  for (const field of ['title', 'description', 'date']) {
    if (!metadata[field]) throw new Error(`${filename}: missing ${field}`);
  }

  const slug = basename(filename, '.md');
  const date = new Date(`${metadata.date}T00:00:00Z`);
  if (Number.isNaN(date.valueOf())) throw new Error(`${filename}: invalid date`);
  if (metadata.external_url) {
    try { new URL(metadata.external_url); }
    catch { throw new Error(`${filename}: invalid external_url`); }
  }
  if (metadata.canonical_url) {
    try { new URL(metadata.canonical_url); }
    catch { throw new Error(`${filename}: invalid canonical_url`); }
  }

  return {
    ...metadata,
    slug,
    date,
    displayDate: new Intl.DateTimeFormat('en', {
      year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC'
    }).format(date),
    body: marked.parse(match[2], { gfm: true })
  };
}

function renderPost(post) {
  const replacements = {
    title: escapeHtml(post.title),
    description: escapeHtml(post.description),
    date: post.date.toISOString().slice(0, 10),
    displayDate: escapeHtml(post.displayDate),
    label: escapeHtml(post.label || 'field notes'),
    canonical: post.canonical_url
      ? `<link rel="canonical" href="${escapeHtml(post.canonical_url)}">`
      : '',
    content: post.body
  };

  return Object.entries(replacements).reduce(
    (html, [key, value]) => html.replaceAll(`{{${key}}}`, value),
    template
  );
}

const filenames = (await readdir(contentDir)).filter(name => name.endsWith('.md'));
const posts = await Promise.all(filenames.map(async filename =>
  parsePost(await readFile(join(contentDir, filename), 'utf8'), filename)
));
posts.sort((a, b) => b.date - a.date);

await mkdir(outputDir, { recursive: true });
await Promise.all(posts.filter(post => !post.external_url).map(post =>
  writeFile(join(outputDir, `${post.slug}.html`), renderPost(post))
));

const listing = posts.map(({ title, description, date, displayDate, label, source, external_url, slug }) => ({
  title, description, date: date.toISOString().slice(0, 10), displayDate,
  label: label || 'field notes', source: source || '',
  external: Boolean(external_url), url: external_url || `posts/${slug}.html`
}));
await writeFile(
  join(root, 'js', 'blog-posts.js'),
  `// Generated by npm run build:blog. Edit content/posts/*.md instead.\nwindow.BLOG_POSTS = ${JSON.stringify(listing, null, 2)};\n`
);

console.log(`Built ${posts.length} blog post${posts.length === 1 ? '' : 's'}.`);
